###### TEXT ######
BOLD := \033[1m
BLACK := \033[30m
RED := \033[31m
GREEN := \033[32m
YELLOW := \033[33m
BLUE := \033[34m
MAGENTA := \033[35m
CYAN := \033[36m
WHITE := \033[37m
RESET := \033[0m

###### BACKGROUND ######
BLACK_BG := \033[40m
RED_BG := \033[41m
GREEN_BG := \033[42m
YELLOW_BG := \033[43m
BLUE_BG := \033[44m
MAGENTA_BG := \033[45m
CYAN_BG := \033[46m
WHITE_BG := \033[47m

define echo_info
	echo $(ECHO_ARGS) "$(GREEN)$(1)$(RESET)"
endef

define echo_error
	echo $(ECHO_ARGS) "$(RED)$(1)$(RESET)"
endef

###### OS DETECTION ######
ifeq ($(OS),Windows_NT)
	DETECTED_OS := Windows
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		DETECTED_OS := Linux
	endif
	ifeq ($(UNAME_S),Darwin)
		DETECTED_OS := macOS
	endif
endif

.phony: clean-all
clean-all: ## Clean all cache and temp files generated by running the project, including files in virtual environment and runs a sync
	@find ./ -depth -type d -name '__pycache__' -exec rm -vrf {} \;
	@find ./ -name '*.pyc' -exec rm -vrf {} \;
	@find ./ -name 'Thumbs.db' -exec rm -vrf {} \;
	@find ./ -name '*~' -exec rm -vrf {} \;
	rm -rf artifacts
	rm -rf .cache
	rm -rf build
	rm -rf dist
	rm -rf *.egg-info
	rm -rf htmlcov
	rm -rf .tox/
	rm -rf docs/_build
	uv sync --all-packages

.phony: clean
clean: ## Clean all cache and temp files generated by running the project, excluding files in virtual environment and runs a sync
	@find ./src -depth -type d -name '__pycache__' -exec rm -vrf {} \;
	@find ./src -name '*.pyc' -exec rm -vrf {} \;
	@find ./src -name 'Thumbs.db' -exec rm -vrf {} \;
	@find ./src -name '*~' -exec rm -vrf {} \;
	rm -rf artifacts
	rm -rf .cache
	rm -rf build
	rm -rf dist
	rm -rf *.egg-info
	rm -rf htmlcov
	rm -rf .tox/
	rm -rf docs/_build
	uv sync --all-packages

.phony: dev-setup
dev-setup: ## Setup the local development environment with virtual environment and dependencies
	@ $(call echo_info, Setting up development environment with uv...)
	@( \
		curl -LsSf https://astral.sh/uv/install.sh | sh; \
		uv python install cpython@3.14.4; \
		uv sync --all-packages; \
		pre-commit install; \
	)
	@ $(call echo_info, Development enviroment setup complete.)

.phony: code-style-check
code-style-check: ## Run code quality checks
	@(\
		. $(PYTHON_BIN)/activate; \
		uv run ruff check; \
	)
	

.phony: code-style-pre-format
code-style-pre-format: ## Fix code style issues
	@(\
		. $(PYTHON_BIN)/activate; \
		uv run ruff check --fix; \
	)
	

.phony: code-style-format
code-style-format: ## Format code
	@(\
		. $(PYTHON_BIN)/activate; \
		uv run ruff format; \
	)

.phony: code-static-check
code-static-check: ## Code static typing check with mypy
	@(\
		. $(PYTHON_BIN)/activate; \
		uv run mypy src; \
	)

.phony: quality-check
quality-check: ## Perform an unit test running
	@(\
		. $(PYTHON_BIN)/activate; \
		uv run pytest tests/ -s -x --cov=src -vv; \
	)

.phony: coverage-check
coverage-check: ## Generate coverage report
	@(\
		. $(PYTHON_BIN)/activate; \
		uv run coverage; \
	)

.phony: run
run: ## Run the project
	@(. $(PYTHON_BIN)/activate)
	uv run bank-api

.phony: help
help: ## Show this help message
	@echo $(ECHO_ARGS) "$(BLACK)$(BOLD)$(GREEN_BG) Available Tasks: $(RESET)"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  $(YELLOW)%-25s$(RESET) %s\n", $$1, $$2}'

###### DEFINITIONS ######
.DEFAULT_GOAL := help
export ANSICON = 1

ifeq ($(DETECTED_OS),Windows)
	PYTHON_BIN ?= .venv/Scripts
		ECHO_ARGS ?= '-e'
		PYTHON_SETUP ?= 'python'
else
	PYTHON_BIN ?= .venv/bin
		ECHO_ARGS ?= ''
		PYTHON_SETUP ?= 'python3'
endif