from _typeshed import Incomplete

class AccountNotFoundError(Exception): ...
class BusinessError(Exception): ...

class InsufficientFundsError(Exception):
    funds: Incomplete
    def __init__(self, funds: float) -> None: ...
